homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /subjects
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
